### ISSUE TITLE
Q30 Model06 Simulation

### ISSUE THREAD

**Issue by LuanaVilela** [lnls-ima/si-quadrupoles-q30#1]
Main coil:
 si-quadrupoles-q30/model-06/simulation/magnetic/2017-02-24_Q30_Model06_Sim_X=-14_14mm_Z=-500_500mm_Imc=153.8A_Itc=0A.txt 

Main coil + Trim coil:
 si-quadrupoles-q30/model-06/simulation/magnetic/2017-02-24_Q30_Model06_Sim_X=-14_14mm_Z=-500_500mm_Imc=153.8A_Itc=10A.txt

**Comment by xresende** [comment]
fmap analysis done. multipoles seem ok. DA calc pending. integrated quadrupoles fall slightly short the spec but are acceptable. 
[analise quadrupolos.txt](https://github.com/lnls-ima/si-quadrupoles-q30/files/896256/analise.quadrupolos.txt)

**Comment by xresende** [comment]
DA calculations finished. new quadrupole model approved.
